Django-Chat/urls.py
from django.contrib import admin
from django.urls import path, re_path
from chat_app import views as chat_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', chat_views.IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('logout/', chat_views.user_logout, name='logout'),
    path('chat', login_required(chat_views.ChatRoomView.as_view(), login_url='home'), name='chat'),
    path('dialogs', login_required(chat_views.DialogsView.as_view(), login_url='home'), name='dialogs'),
    re_path(r'^dialogs/create/(?P<user_id>\d+)/$', chat_views.CreateDialogView.as_view(), name='create_dialog'),
    re_path(r'^dialogs/(?P<chat_id>\d+)/$', login_required(chat_views.MessagesView.as_view(), login_url='home'),
            name='messages')
]

chat_app/models.py
from django.db import models

from django.contrib.auth.models import User
from datetime import datetime

class Chat(models.Model):
    members = models.ManyToManyField(User)

    @models.permalink
    def get_absolute_url(self):
        return 'messages', (), {'chat_id': self.pk }

class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=True)
    author = models.ForeignKey(User, on_delete=True)
    message = models.TextField()
    pub_date = models.DateTimeField(verbose_name='Timestamp of message',default=datetime.now)

    class Meta:
        ordering=['pub_date']

    def __str__(self):
        return self.message

chat_app/forms.py
from chat_app.models import Message
from django.forms import ModelForm

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

chat_app/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.utils import timezone
from django.views import View
from chat_app.models import Chat
from chat_app.forms import MessageForm
import re


class IndexView(View):
    def get(self, request):
        # If user is authenticated - redirect him/her to chat rooms
        if request.user.id:
            return redirect('chat')
        else:
            # else allow user to login / register
            signup_form = UserCreationForm()
            return render(request, 'index.html', {'signup_form': signup_form})

    def post(self, request):
        # If user tries to login
        if request.POST.get('submit') == 'sign_in':
            # First get the username and password supplied
            username = request.POST.get('username')
            password = request.POST.get('password')

            # Authenticate user
            user = authenticate(username=username, password=password)

            # If user exists
            if user:
                # Log the user in
                login(request, user)
                return redirect('chat')
            else:
                return HttpResponse("Invalid login details supplied.")  # TODO: Login error handling

        # If user tries to signup
        elif request.POST.get('submit') == 'sign_up':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('home')
            else:
                return HttpResponse("Invalid registration form")  # TODO: Signup error handling


def user_logout(request):
    # Log out the user
    logout(request)
    return redirect('home')


class ChatRoomView(View):
    def get(self, request):
        # Show ChatRoom with all online users
        # TODO List of online users doesnt seem to be working reliably
        active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
        user_id_list = []
        for session in active_sessions:
            data = session.get_decoded()
            user_id_list.append(data.get('_auth_user_id', None))

        # Query all logged in users based on id list
        online_users = User.objects.filter(id__in=user_id_list)
        return render(request, 'chat_app/chat_room.html', {'users': online_users})


class DialogsView(View):
    def get(self, request):
        chats = Chat.objects.filter(members__in=[request.user.id])
        return render(request, 'chat_app/dialogs.html', {'user_profile': request.user, 'chats': chats})


class CreateDialogView(View):
    def get(self, request, user_id):
        # Query all chats where either of users appear and find the common(id)
        ch1 = Chat.objects.filter(members=request.user.id).values_list('id')
        ch2 = Chat.objects.filter(members=user_id).values_list('id')

        # TODO - It's a mess, find a better way to query and extract chat id
        try:
            chat_id = [int(s) for s in re.findall(r'-?\d+\.?\d*', str(set(ch1).intersection(ch2)))][0]
            chat = Chat.objects.get(id=chat_id)
        except IndexError:
            # If chat is not existing - create new
            chat = Chat.objects.create()
            chat.members.add(request.user)
            chat.members.add(user_id)
        return redirect(reverse('messages', kwargs={'chat_id': chat.id}))


class MessagesView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
        except Chat.DoesNotExist:
            chat = None

        return render(
            request,
            'chat_app/messages.html',
            {
                'user_profile': request.user,
                'chat': chat,
                'form': MessageForm()
            }
        )

    def post(self, request, chat_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat_id = chat_id
            message.author = request.user
            message.save()
        return redirect(reverse('messages', kwargs={'chat_id': chat_id}))

templates/_includes/navbar.html
<!--Mainmenu-area-->
<div class="mainmenu-area" data-spy="affix" data-offset-top="100">
    <div class="container">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary-menu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand logo">
                <h2>JobyChat</h2>by Jobylon
            </a>
        </div>
        <!--Logo/-->
        <nav class="collapse navbar-collapse" id="primary-menu">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'chat' %}">Chat room</a></li>
                    <li><a href="{% url 'dialogs' %}">My discussions</a></li>
                    <li><a href="{% url 'logout' %}">Logout ({{ user.username }})</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<!--Mainmenu-area/-->

templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Place favicon.ico in the root directory -->
    <link rel="apple-touch-icon" href="{% static "images/apple-touch-icon.png" %}">
    <link rel="shortcut icon" type="image/ico" href="{% static "images/favicon.ico" %}"/>
    <!-- Plugin-CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/themify-icons.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <!-- Main-Stylesheets -->
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "style.css" %}">
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">
    <script src="{% static "js/vendor/modernizr-2.8.3.min.js" %}"></script>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>JobyChat - {% block title %}Chat{% endblock %}</title>

</head>
<body data-spy="scroll" data-target="#primary-menu" class="sky-bg">


<div class="preloader">
    <div class="sk-folding-cube">
        <div class="sk-cube1 sk-cube"></div>
        <div class="sk-cube2 sk-cube"></div>
        <div class="sk-cube4 sk-cube"></div>
        <div class="sk-cube3 sk-cube"></div>
    </div>
</div>

{% include '_includes/navbar.html' %}


{% block content %}{% endblock %}


<!--Vendor-JS-->
<script src="{% static "js/vendor/jquery-1.12.4.min.js" %}"></script>
<script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
<!--Plugin-JS-->
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/contact-form.js" %}"></script>
<script src="{% static "js/jquery.parallax-1.1.3.js" %}"></script>
<script src="{% static "js/scrollUp.min.js" %}"></script>
<script src="{% static "js/magnific-popup.min.js" %}"></script>
<script src="{% static "js/wow.min.js" %}"></script>
<!--Main-active-JS-->
<script src="{% static "js/main.js" %}"></script>
</body>
</html>
</head>

templates/chat_app/chat_room.html
{% extends 'base.html' %}

{% block title %}Chat room{% endblock %}

{% block content %}
    <header class="header-area overlay full-height relative v-center" id="home-page">
        <div class="absolute anlge-bg"></div>
        <div class="container">
            <div class="row v-center">
                <div class="col-xs-12 col-md-7 header-text">
                    <h2>Hey, {{ user.username }}!</h2>
                    <p>To start chatting, please click on any currently online users</p>
                    <p style="font-size: smaller">You can also click <a href="{% url 'dialogs' %}">"My discussions"</a>
                        to see the archive
                        of your conversations</p>
                </div>
                <div class="col-md-1"></div>

                <div class="hidden-xs hidden-sm col-md-4 text-right">
                    <div class="card" style="width: 18rem;">
                        <div class="card-header">
                            <h3>Currently online users</h3>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% if users.count > 1 %}
                                {% for usr in users %}
                                    {% if usr.id != user.id %}
                                        <li class="list-group-item">
                                            <a href="{% url 'create_dialog' user_id=usr.id %}"
                                               style="color: #515656">{{ usr.username }}</a>
                                            <i class="fa fa-user" style="color: #515656"></i>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <li class="list-group-item" style="color: #515656">
                                    No online users
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </header>
{% endblock %}

templates/chat_app/dialogs.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}Private chat{% endblock %}
{% block content %}
    <div>

        {% if chats.count == 0 %}
            <div class="chat_container">
                <div class="messaging">
                    <h2>Sorry, you have no conversations yet.</h2>
                    <h2>But you can go to <a href="{% url 'chat' %}">Chat Room</a> and start chatting!</h2>
                </div>
            </div>
        {% else %}
            <div class="chat_container">
                <div class="messaging">
                    <div class="inbox_msg">
                        <div class="inbox_people">
                            <div class="headind_srch">
                                <div class="recent_heading">
                                    <h4>All Discussions</h4>
                                </div>
                            </div>
                            <div class="inbox_chat">
                                {% for chat in chats %}
                                    {% if chat.message_set.count != 0 %}
                                        {% get_companion user chat as companion %}
                                        <div class="chat_list">
                                            <div class="chat_people"
                                            ">
                                            <div class="chat_img"><img
                                                    src="https://ptetutorials.com/images/user-profile.png"
                                                    alt="sunil">
                                            </div>
                                            <div class="chat_ib">
                                                <h5>{{ companion.username }}
                                                    <span class="chat_date"><a href="{{ chat.get_absolute_url }}"> Click here to see full conversation</a></span>
                                                </h5>
                                                <p>Here you can see your full conversation
                                                    with {{ companion.username }}</p>
                                            </div>
                                        </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            </div>
            </div>
        {% endif %}
    </div>


{% endblock %}

templates/chat_app/messages.html
{% extends 'base.html' %}
{% load tz %}
{% load custom_tags %}
{% load static %}

{% block title %}Private chat{% endblock %}
{% block content %}
    <div class="container-fluid">
        {% if not chat %}
            User not found or you dont have access
        {% elif chat %}
            <div class="chat_container">
                <div class="messaging">
                    <h3>Conversetion with {% get_companion user chat as companion %}<span
                            style="color: #515656">{{ companion }}</span></h3>
                    <div class="inbox_msg">
                        <div class="mesgs inbox_people">
                            <div class="msg_history">
                                {% for message in chat.message_set.all %}
                                    {% if message.author.username == user.username %}
                                        <div class="outgoing_msg">
                                            <div class="sent_msg">
                                                <p>{{ message.message|safe }}</p>
                                                <span class="time_date"> {{ message.pub_date|utc }}</span>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="incoming_msg">
                                            <div class="incoming_msg_img">
                                                <img src="{% static 'images/user-profile.png' %}" alt="sunil">
                                            </div>
                                            <div class="received_msg">
                                                <div class="received_withd_msg">
                                                    <p>{{ message.message|safe }}</p>
                                                    <span class="time_date"> {{ message.pub_date|utc }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}

                                <div class="type_msg">
                                    <div class="input_msg_write">
                                        <form method="post">
                                            {% csrf_token %}
                                            <input type="text" name="message" class="write_msg"
                                                   placeholder="Type a message"/>
                                            <button class="msg_send_btn" type="submit"><i class="fa fa-paper-plane-o"
                                                                                          aria-hidden="true"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <header class="header-area overlay full-height relative v-center" id="home-page">
        <div class="absolute anlge-bg"></div>
        <div class="container">
            <div class="row v-center">
                <div class="col-xs-12 col-md-7 header-text">
                    <h2>Login to use our JobyChat</h2>
                    <p>We are happy to see you back! Type in your username and password and let's chat!</p>
                    <form method="post" class="contact-form">
                        {% csrf_token %}
                        <div class="form-double">
                            <input class="form-control" type="text" name="username" placeholder="Username"
                                   required="required">
                            <input class="form-control" type="password" name="password" placeholder="Password"
                                   required="required">
                        </div>
                        <button class="button white" type='submit' name='submit' value='sign_in'>Login</button>
                    </form>
                </div>
                <div class="col-md-1"></div>
                <div class="hidden-xs hidden-sm col-md-4 text-right">
                    <h2>Sign up</h2>
                    <p>If you don't have an account yet, it's simple to create!</p>
                    <form method="post" class="contact-form">
                        {% csrf_token %}
                        {% for field in signup_form %}
                            <input class="form-control" name="{{ field.name }}" placeholder="{{ field.label }}"
                                   required="required"
                                   {% if field.name == 'password1' or field.name == 'password2' %}type="password"{% endif %}>
                        {% endfor %}
                        <button class="button white" type='submit' name='submit' value='sign_up'>Sign up</button>
                    </form>
                </div>
            </div>
        </div>
    </header>
{% endblock %}